
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-django
    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DB_ENGINE: ${DJANGO_DB_ENGINE}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      MYSQL_DB_HOST: ${MYSQL_DB_HOST}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      MYSQL_DB_USER: ${MYSQL_DB_USER}
      MYSQL_DB_PASS: ${MYSQL_DB_PASS}
      MYSQL_DB_PORT: ${MYSQL_DB_PORT}
      BINANCE_TSTNET_URL: ${BINANCE_TSTNET_URL}
      BINANCE_TSTNET_KEY: ${BINANCE_TSTNET_KEY}
      BINANCE_TSTNET_SECRET: ${BINANCE_TSTNET_SECRET}
      
    volumes:
      - ./app:/app
    networks:
      - app-trader
    ports:
      - "443:443"
      - "8000:8000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4
    command: --innodb-use-native-aio=0
    restart: always
    container_name: app-mysql
    networks:
      - app-trader
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASS}
    volumes:
      - ./mysql/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p${MYSQL_DB_PASS}", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s    

networks:
  app-trader:
