AWSTemplateFormatVersion: "2010-09-09"
Description: "RDS MySQL Instance"

Parameters:
  DBNAME:
    Type: String
    NoEcho: true

  DBUSERNAME:
    Type: String
    NoEcho: true

  DBPASSWORD:
    Type: String
    NoEcho: true

Resources:

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for MySQL DB Instance
      VpcId: !ImportValue VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 10.0.0.0/24

  MySqlDBInstance:
      Type: "AWS::RDS::DBInstance"
      Properties:
          DBInstanceIdentifier: "django-mysql-db"
          AvailabilityZone: "us-east-1a"
          AllocatedStorage: "20"
          DBInstanceClass: "db.t3.micro"
          Engine: "mysql"
          EngineVersion: "8.0.35"
          MasterUsername: !Ref "DBUSERNAME"
          MasterUserPassword: !Ref "DBPASSWORD"
          DBName: !Ref "DBNAME"
          StorageType: "gp2"
          PubliclyAccessible: false
          BackupRetentionPeriod: 1
          AutoMinorVersionUpgrade: true
          VPCSecurityGroups: 
              - !Ref DBSecurityGroup

Outputs:
  MySqlDBEndpoint:
    Description: "MySQL DB endpoint"
    Value: !GetAtt MySqlDBInstance.Endpoint.Address
    Export:
      Name: "MySqlDBEndpoint"

  MySqlDBPort:
    Description: "MySQL DB port"
    Value: !GetAtt MySqlDBInstance.Endpoint.Port
    Export:
      Name: "MySqlDBPort"
