AWSTemplateFormatVersion: "2010-09-09"
Description: "RDS MySQL Instance"

Parameters:
  DBName:
    Type: String
    Description: "Database name"    

  DBUsername:
    Type: String
    Description: "Database master username"
    NoEcho: true

  DBPassword:
    Type: String
    Description: "Database master password"
    NoEcho: true

  SubnetId1:
    Type: "AWS::EC2::Subnet::Id"
    Description: "First subnet ID for the DB subnet group"

  SubnetId2:
    Type: "AWS::EC2::Subnet::Id"
    Description: "Second subnet ID for the DB subnet group"

  VPCId:
    Type: "AWS::EC2::VPC::Id"
    Description: "The ID of the VPC"  
          
  VPCSecurityGroupId:
    Type: "AWS::EC2::SecurityGroup::Id"
    Description: "VPC security group ID"
    Default: "sg-0872544ac634aad83"

Resources:
  MySqlDBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties: 
      DBSubnetGroupDescription: "Subnet group for MySQL RDS"
      SubnetIds: 
        - !Ref SubnetId1
        - !Ref SubnetId2

  MySqlDBInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      
      LicenseModel": "general-public-license"
      DBInstanceIdentifier: "django-mysql-db"
      AllocatedStorage: 20
      DBInstanceClass: "db.t3.micro"
      Engine: "mysql"
      EngineVersion: "8.0.35"
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBName: !Ref DBName
      DBSubnetGroupName: !Ref MySqlDBSubnetGroup
      VPCSecurityGroups:
        - !Ref VPCSecurityGroupId
      PubliclyAccessible: false
      StorageType: "gp2"
      SupportedNetworkTypes: "IPV4"
      MultiAZ: false

Outputs:
  MySqlDBEndpoint:
    Description: "MySQL DB endpoint"
    Value: !GetAtt MySqlDBInstance.Endpoint.Address
  MySqlDBPort:
    Description: "MySQL DB port"
    Value: !GetAtt MySqlDBInstance.Endpoint.Port
