AWSTemplateFormatVersion: "2010-09-09"
Description: "RDS MySQL Instance"

Parameters:
  DBName:
    Type: String
    Description: "Database name"    

  DBUsername:
    Type: String
    Description: "Database master username"
    NoEcho: true

  DBPassword:
    Type: String
    Description: "Database master password"
    NoEcho: true

Resources:
MySqlDBInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceIdentifier: "django-mysql-db"
      AllocatedStorage: 20
      DBInstanceClass: "db.t3.micro"
      Engine: "mysql"
      EngineVersion: "8.0.35"
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBName: !Ref DBName
      PubliclyAccessible: false
      StorageType: "gp2"
      MultiAZ: false
      BackupRetentionPeriod: 2
      AutoMinorVersionUpgrade: false
      DeletionProtection: false
      EnableIAMDatabaseAuthentication: true
      SupportedNetworkTypes:
        - "IPv4"


      
      