AWSTemplateFormatVersion: "2010-09-09"
Description: "RDS MySQL Instance"

Parameters:
  DBInstanceIdentifier:
    Type: String
    Description: "Database instance identifier"
    NoEcho: false

  DBName:
    Type: String
    Description: "Database name"
    NoEcho: false

  DBUsername:
    Type: String
    Description: "Database master username"
    NoEcho: true

  DBPassword:
    Type: String
    Description: "Database master password"
    NoEcho: true

  DBAllocatedStorage:
    Type: Number
    Description: "The allocated storage size in gigabytes"
    Default: 20  

  DBInstanceClass:
    Type: String
    Description: "Database instance class"
    Default: "db.t3.micro"

  SubnetId1:
    Type: "AWS::EC2::Subnet::Id"
    Description: "First subnet ID for the DB subnet group"

  SubnetId2:
    Type: "AWS::EC2::Subnet::Id"
    Description: "Second subnet ID for the DB subnet group"

  VPCId:
    Type: "AWS::EC2::VPC::Id"
    Description: "The ID of the VPC"

Resources:
  MySqlDBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties: 
      DBSubnetGroupDescription: "Subnet group for MySQL RDS"
      SubnetIds: 
        - !Ref SubnetId1
        - !Ref SubnetId2

  MySqlDBInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      AllocatedStorage: !Ref DBAllocatedStorage
      DBInstanceClass: !Ref DBInstanceClass
      Engine: "MySQL"
      EngineVersion: "8.0.35"
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBName: !Ref DBName
      VPCSecurityGroups:
        - "sg-0872544ac634aad83"
      DBSubnetGroupName: !Ref MySqlDBSubnetGroup
      PubliclyAccessible: false
      MultiAZ: false

Outputs:
  MySqlDBEndpoint:
    Description: "MySQL DB endpoint"
    Value: !GetAtt MySqlDBInstance.Endpoint.Address
  MySqlDBPort:
    Description: "MySQL DB port"
    Value: !GetAtt MySqlDBInstance.Endpoint.Port
