name: Deploy IaC VPC/RDS/ECS

on:
  workflow_dispatch:

jobs:
  deploy-vpc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy VPC
        run: |
          aws cloudformation deploy \
            --template-file aws/vpc-deploy.yml \
            --stack-name vpc-stack \
            --capabilities CAPABILITY_NAMED_IAM

  deploy-rds:
    needs: deploy-vpc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy RDS
        run: |
          aws cloudformation deploy \
            --template-file aws/rds-deploy.yml \
            --stack-name rds-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              DBNAME=${{ vars.MYSQL_DB_NAME }} \
              DBUSERNAME=${{ vars.MYSQL_DB_USER }} \
              DBPASSWORD=${{ secrets.MYSQL_DB_PASS }}

      - name: Wait for RDS stack complete
        run: aws cloudformation wait stack-create-complete --stack-name rds-stack

  deploy-ecs:
    needs: deploy-rds 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy ECS
        run: |
          aws cloudformation deploy \
            --template-file aws/ecs-deploy.yml \
            --stack-name ecs-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              DjangoSecretKey=${{ secrets.DJANGO_SECRET_KEY }} \
              MysqlDbPass=${{ secrets.MYSQL_DB_PASS }}
