name: Deploy IAC VPC-RDS-ECS

on:
  workflow_dispatch:

jobs:
  deploy-vpc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy VPC
        run: |
          aws cloudformation deploy --template-file aws/vpc-deploy.yml --stack-name vpc-stack --capabilities CAPABILITY_NAMED_IAM

      - name: Get VPC Outputs
        id: vpc-outputs
        run: |
          echo "VPC_ID=$(aws cloudformation describe-stacks --stack-name vpc-stack --query "Stacks[0].Outputs[?OutputKey=='VPCId'].OutputValue" --output text)" >> $GITHUB_ENV
          echo "SUBNET_ID=$(aws cloudformation describe-stacks --stack-name vpc-stack --query "Stacks[0].Outputs[?OutputKey=='SubnetId'].OutputValue" --output text)" >> $GITHUB_ENV
  
  deploy-rds:
    needs: deploy-vpc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy RDS
        run: |
          aws cloudformation deploy --template-file aws/rds-deploy.yml --stack-name rds-stack --capabilities CAPABILITY_NAMED_IAM --parameter-overrides VPCID=${{ env.VPC_ID }} DBNAME=${{ vars.MYSQL_DB_NAME }} DBUSERNAME=${{ vars.MYSQL_DB_USER }} DBPASSWORD=${{ secrets.MYSQL_DB_PASS }}

      - name: Get RDS Outputs
        id: rds-outputs
        run: |
          echo "RDS_ENDPOINT=$(aws cloudformation describe-stacks --stack-name rds-stack --query 'Stacks[0].Outputs[?OutputKey==\"MySqlDBEndpoint\"].OutputValue' --output text)" >> $GITHUB_ENV

  deploy-ecs:
    needs: deploy-rds 
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy ECS
        run: |
          aws cloudformation deploy \
            --template-file aws/ecs-deploy.yml \
            --stack-name ecs-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              MYSQL_DB_HOST=${{ env.RDS_ENDPOINT }} \
              DjangoSecretKey=${{ secrets.DJANGO_SECRET_KEY }} \
              MysqlDbPass=${{ secrets.MYSQL_DB_PASS }}
